on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 13
      - run: |
          yarn install
          npm install -g ts-node esm typescript@next nyc
          export PATH="$PATH:/usr/local/share/.config/yarn/global/node_modules"
      - run: yarn run coverage
